version: '3.0'

services:
  proxy-dev:
    container_name: nginx-proxy-dev
    network_mode: "host"
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_PORT=80
      - NGINX_ENTRYPOINT_QUIET_LOGS=0
    extra_hosts:
      - "host.docker.internal:host-gateway"

